sudo: true
dist: trusty 
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
# d elete the following line before encrypting your server.key
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx force:auth:jwt:grant --clientid 3MVG9d8..z.hDcPII_BNIfrPsLj9vPqwYcAycBrtSUlhZ3WYAQdZ1dBpYnsuUEz7h.3e1.R.U2autAH5eOB3f
 --jwtkeyfile assets/server.key --username mrmoser1@verizon.net.hub --setdefaultdevhubusername -a HubOrg

script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p